version: 2
updates:
  # Python (e.g., for a microservice using `pip` or `poetry`)
  - package-ecosystem: "pip"
    directory: "/zoo-python-fastapi" # Location of requirements.txt in the microservice directory
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "python"
    target-branch: "main" # Optional: specify the target branch

  # Python (e.g., for a microservice using `pip` or `poetry`)
  - package-ecosystem: "pip"
    directory: "/zoo-python-flask" # Location of requirements.txt in the microservice directory
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "python"
    target-branch: "main" # Optional: specify the target branch
    
  # Composer (PHP dependencies)
  - package-ecosystem: "composer"
    directory: "/zoo-php-laravel"  # Location of composer.json in the microservice directory
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"  # Check for updates every day
    ignore:
      - dependency-name: "php"  # Ignore updates to PHP itself (if needed)
    commit-message:
      prefix: "php"
    target-branch: "main" # Optional: specify the target branch

  # NPM (JavaScript dependencies)
  - package-ecosystem: "npm"
    directory: "/zoo-typescript-angular"  # Location of package.json in the microservice directory
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"  # Check for updates every day
    commit-message:
      prefix: "npm"
    target-branch: "main" # Optional: specify the target branch

  # NPM (JavaScript dependencies)
  - package-ecosystem: "npm"
    directory: "/zoo-typescript-react"  # Location of package.json in the microservice directory
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"  # Check for updates every day
    commit-message:
      prefix: "npm"
    target-branch: "main" # Optional: specify the target branch