apiVersion: v2
name: zoo-typescript-angular
description: Typescript-Angular microservice for Zoo project
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: zoo-common
    version: 0.1.0
    repository: "file://../zoo-common"
