replicaCount: 1

image:
  repository: ghcr.io/intelligent002/zoo/zoo-typescript-angular
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  APP_PORT: "8080"
  DEBUG_MODE: "False"
  ENVIRONMENT: "DEVELOPMENT"
  LOG_LEVEL: "DEBUG"
  SERVICE_NAME: "zoo-typescript-angular"
  NGINX_PORT: "8080"

# HTTP health checks for FastAPI
startupProbe:                # startup probe, delays other probes
  httpGet:
    path: /liveness
    port: 8080
  initialDelaySeconds: 5     # wait 5s before first probe
  periodSeconds: 5           # then probe every 5s
  failureThreshold: 5        # 5×5s = 25s extra grace

livenessProbe:               # self check only
  httpGet:
    path: /liveness
    port: 8080
  initialDelaySeconds: 0     # begins after startupProbe finishes
  periodSeconds: 120         # check only once 2 minutes
  timeoutSeconds: 3
  failureThreshold: 3        # needs 3 failures = ~3 min before pod restart

readinessProbe:              # composite checkup, expensive
  httpGet:
    path: /liveness
    port: 8080
  initialDelaySeconds: 0     # begins after startupProbe finishes
  periodSeconds: 30          # check every 20s
  timeoutSeconds: 2
  failureThreshold: 1        # one fail pulls pod from LB pool

ingress:
  enabled: true

resources: {}
autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: default