services:

    # MySQL Service
    zoo-mysql:
        image: docker.artifactory.intel.r7g.org/mysql:8.0
        container_name: zoo-mysql
        restart: unless-stopped
        ports:
            - "3307:3307"
        environment:
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_DATABASE: zoo-db
            MYSQL_USER: zoo-user
            MYSQL_PASSWORD: zoo-password
            MYSQL_HOSTNAME: localhost
            MYSQL_TCP_PORT: 3307
        volumes:
            - mysql-data:/var/lib/mysql
            - ./zoo-mysql/mysql-health.sh:/mysql-health.sh
        entrypoint: ["/bin/bash", "-c", "chmod +x /mysql-health.sh && docker-entrypoint.sh mysqld"]
        healthcheck:
            # Test availabiltiy of mysql service, listening & actually serving - via mounted script
            test: [ "CMD", "/mysql-health.sh" ]
            interval: 60s
            retries: 5
            start_period: 20s
            timeout: 10s
        networks:
            - zoo

    # Backend written in Python/Flask (python:3.12.5-alpine3.20)
    zoo-python-flask:
        build:
            context: ./zoo-python-flask # Set build context to the respective folder
            dockerfile: Dockerfile
        container_name: zoo-python-flask
        restart: unless-stopped
        environment:
            - DB_HOSTNAME=zoo-mysql
            - DB_USERNAME=zoo-user
            - DB_PASSWORD=zoo-password
            - DB_DATABASE=zoo-db
            - DB_PORT=3307
            - DEBUG_MODE=False
            - LOG_LEVEL=DEBUG
            - APP_PORT=8101
        healthcheck:
            # Test availabiltiy of gunicorn service, listening & serving - via inline curl request parsed by JQ
            test: ["CMD-SHELL", "response=$$(curl -s http://localhost:8101/graphql/liveness | jq -r '.status'); \
                    if [ \"$$response\" != \"OK\" ]; then echo \"Status is not OK\" && exit 1; else echo \"Status is OK\" && exit 0; fi"]
            interval: 60s
            retries: 3
            start_period: 5s
            timeout: 10s
        ports:
            - "8101:8101"
        depends_on:
            - zoo-mysql
        networks:
            - zoo

    # Frontend written in TypeScript/React (node:18-alpine3.20)
    zoo-typescript-react:
        build:
            context: ./zoo-typescript-react # Set build context to the respective folder
            dockerfile: Dockerfile
        container_name: zoo-typescript-react
        restart: unless-stopped
        environment:
            - LOG_LEVEL=DEBUG
            - NGINX_PORT=8102
            - REACT_APP_ROUTER_PORT=8120
        healthcheck:
            # Test availabiltiy of nginx service, listening & serving - via inline curl request parsed by JQ
            test: ["CMD-SHELL", "response=$$(curl -s http://localhost:8102/liveness | jq -r '.status'); \
                    if [ \"$$response\" != \"OK\" ]; then echo \"Status is not OK\" && exit 1; else echo \"Status is OK\" && exit 0; fi"]
            interval: 60s
            retries: 3
            start_period: 5s
            timeout: 10s
        ports:
            - "8102:8102"
        depends_on:
            - zoo-python-flask
        networks:
            - zoo

    # Backend written in PHP/Laravel (php:8.2-fpm)
    zoo-php-laravel:
        build:
            context: ./zoo-php-laravel # Set build context to the respective folder
            dockerfile: Dockerfile
            args:
                APP_URL: "http://localhost:8003/"
        container_name: zoo-php-laravel
        restart: unless-stopped
        environment:
            - APP_URL=http://localhost:8003/
            - DB_HOSTNAME=zoo-mysql
            - DB_PASSWORD=zoo-password
            - DB_DATABASE=zoo-db
            - DB_USERNAME=zoo-user
            - DB_PORT=3307
            - APP_PORT=8103
        volumes:
            - ./zoo-mysql/mysql-wait.sh:/mysql-wait.sh:rw
        healthcheck:
            # Test availabiltiy of php-fpm service, listening & serving - via inline cgi-fcgi request parsed by JQ
            test: ["CMD-SHELL", "response=$$(REQUEST_URI=/rest/liveness SCRIPT_FILENAME=/var/www/html/public/index.php REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:8103 | sed -n '/^{/,$$p' | jq -r '.status'); \
                    if [ \"$$response\" != \"OK\" ]; then echo \"Status is not OK\" && exit 1; else echo \"Status is OK\" && exit 0; fi"]
            interval: 60s
            retries: 3
            start_period: 5s
            timeout: 10s
        ports:
            - "8103:8103"
        depends_on:
            - zoo-mysql
        # dont start the migrations before mysql is really ready to serve requests
        command: ["/bin/sh", "-c", "chmod +x /mysql-wait.sh && /mysql-wait.sh && php artisan migrate --force && php-fpm"]
        networks:
            - zoo

    # NGINX Service (Reverse Proxy + HTTP to PHP-FPM converter + Static File Serving)
    zoo-php-laravel-http2fpm:
        build:
            context: ./zoo-php-laravel-http2fpm # Set build context to the respective folder
            dockerfile: Dockerfile
        container_name: zoo-php-laravel-http2fpm
        restart: unless-stopped
        environment:
            - NGINX_PORT=8104
            - ZOO_PHP_LARAVEL_PORT=8103
        volumes:
            - ./zoo-php-laravel-http2fpm/probe/:/var/www/html/
        healthcheck:
            # Test availabiltiy of nginx service, listening & serving - via inline curl request parsed by JQ
            test: ["CMD-SHELL", "response=$$(curl -s http://localhost:8104/liveness | jq -r '.status'); \
                    if [ \"$$response\" != \"OK\" ]; then echo \"Status is not OK\" && exit 1; else echo \"Status is OK\" && exit 0; fi"]
            interval: 60s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            - zoo-php-laravel
        ports:
            - "8104:8104"
        networks:
            - zoo

    # NGINX Service (Routing + Reverse Proxy + Caching + Static File Serving)
    zoo-router:
        build:
            context: ./zoo-router # Set build context to the respective folder
            dockerfile: Dockerfile
        container_name: zoo-router
        restart: unless-stopped
        environment:
            - NGINX_PORT=8120
            - ZOO_PYTHON_FLASK_PORT=8101
            - ZOO_TYPESCRIPT_REACT_PORT=8102
            - ZOO_PHP_LARAVEL_HTTP2FPM_PORT=8104
        ports:
            - "8120:8120"
        volumes:
            - ./zoo-router/probe/:/var/www/html/
        healthcheck:
            # Test availabiltiy of nginx service, listening & serving - via inline curl request compared as is
            test: ["CMD-SHELL", "response=$$(curl -s http://localhost:8120/liveness | jq -r '.status'); \
                    if [ \"$$response\" != \"OK\" ]; then echo \"Status is not OK\" && exit 1; else echo \"Status is OK\" && exit 0; fi"]
            interval: 60s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            - zoo-typescript-react
            - zoo-python-flask
            - zoo-php-laravel-http2fpm
        networks:
            - zoo

# Named volumes for persistent data storage
volumes:
    mysql-data:

# Shared network between the containers
networks:
    zoo:
        driver: bridge
