global:
  scrape_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  - job_name: 'zoo-python-flask'
    dns_sd_configs:
      - names:
          - 'zoo-python-flask'
        type: 'A'
        port: 8100

  - job_name: 'zoo-python-fastapi'
    dns_sd_configs:
      - names:
          - 'zoo-python-fastapi'
        type: 'A'
        port: 8101

  - job_name: 'zoo-php-laravel-http2fpm'
    dns_sd_configs:
      - names:
          - 'zoo-php-laravel-http2fpm'
        type: 'A'
        port: 8104

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "zoo-alertmanager:9093"  # Alertmanager service name and port in Docker Compose

rule_files:
  - "/etc/prometheus/rules/*.yml"  # Define your alerting rules here
