global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zoo-python-flask'
    static_configs:
      - targets: ['zoo-python-flask:8100']

  - job_name: 'zoo-python-fastapi'
    static_configs:
      - targets: ['zoo-python-fastapi:8101']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "zoo-alertmanager:9093"  # Alertmanager service name and port in Docker Compose

rule_files:
  - "/etc/prometheus/rules/*.yml"  # Define your alerting rules here
