server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://zoo-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            message: message
            timestamp: timestamp
            level: level
            logger_name: logger_name
            environment: environment
            service_name: service_name
            trace_id: trace_id
            request_id: request_id
      - labels:  # Convert fields to labels
          message:
          level:
          environment:
          service_name:
      - timestamp:  # Ensure the logs use the correct timestamp
          source: timestamp
          format: "2006-01-02T15:04:05.000000000Z"
