# Global configuration shared across all services
global:
  namespace: zoo
  image:
    registry: ghcr.io/intelligent002/zoo
  db:
    enabled: true

zoo-mysql:
  db:
    enabled: true
    secretName: zoo-db-secret
  storage:
    size: 3Gi

zoo-python-fastapi:
  replicaCount: 2
  image:
    repository: ghcr.io/intelligent002/zoo/zoo-python-fastapi
    tag: latest
  global:
    db:
      enabled: true
      secretName: zoo-db-secret
  service:
    port: 8101
  ingress:
    enabled: true
    host: public-api.docker.r7g.org

zoo-python-flask:
  replicaCount: 2
  image:
    repository: ghcr.io/intelligent002/zoo/zoo-python-flask
    tag: latest
  global:
    db:
      enabled: true
      secretName: zoo-db-secret
  service:
    port: 8101
  ingress:
    enabled: true
    host: public-api.docker.r7g.org

zoo-php-laravel:
  replicaCount: 2
  image:
    repository: ghcr.io/intelligent002/zoo/zoo-php-laravel
    tag: latest
  global:
    db:
      enabled: true
      secretName: zoo-db-secret
  service:
    port: 8101
  ingress:
    enabled: true
    host: private-api.docker.r7g.org

zoo-typescript-react:
  replicaCount: 2
  image:
    repository: ghcr.io/intelligent002/zoo/zoo-typescript-react
    tag: latest
  service:
    port: 8101
  ingress:
    enabled: true
    host: public.docker.r7g.org
