groups:
  - name: high-cpu-usage
    rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total{mode!="idle"} < 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 5 minutes on {{ $labels.instance }}."
