services:
    # MySQL Service
    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            retries: 5
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    # Laravel Application Service (PHP-FPM-alpine)
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_URL: "http://app:8085"
        container_name: laravel_app
        restart: unless-stopped
        environment:
            - APP_URL=http://localhost:8000/
            - DB_HOST=laravel_mysql
            - DB_DATABASE=laravel_db
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=laravel_password
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        command: /bin/sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
        networks:
            - laravel

    # NGINX Service (Reverse Proxy + Caching + Static File Serving)
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8085:80"  # Expose NGINX on port 8080
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Use custom NGINX config
        depends_on:
            - app
        networks:
            - laravel

# Named volumes for persistent data storage
volumes:
    dbdata:

# Shared network between the containers
networks:
    laravel:
        driver: bridge
