apiVersion: 1
datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://zoo-prometheus:9090"
    isDefault: true
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    editable: true
    jsonData:
      timeInterval: "30s"  # Set the query interval in Grafana
  - name: "Loki"
    type: "loki"
    typeName: "Loki"
    typeLogoUrl: "public/app/plugins/datasource/loki/img/loki_icon.svg"
    access: "proxy"
    url: "http://zoo-loki:3100"
    isDefault: false
    jsonData:
      timeInterval: "30s"  # Set the query interval in Grafana
    editable: true
