apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://zoo-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"  # Set the query interval in Grafana
