{{- $db := .Values.global.db }}
{{- if $db.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-zoo-db-secret" .Release.Name }}
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  MYSQL_HOST: {{ $db.host | default (printf "%s-zoo-mysql" .Release.Name) | quote }}
  MYSQL_PORT: {{ $db.port | default "3306" | quote }}
  MYSQL_BASE: {{ $db.base | default "zoo-db" | quote }}
  MYSQL_USER: {{ $db.user | default "zoo-user" | quote }}
  MYSQL_PASS: {{ $db.pass | default "zoo-pass" | quote }}
  MYSQL_ROOT: {{ $db.root | default "007" | quote }}
{{- end }}