{{- if .Values.global.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.secretName | default "zoo-db-secret" }}
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.global.db.host | default "zoo-all-zoo-mysql" | quote }}
  MYSQL_BASE: {{ .Values.global.db.base | default "zoo-db" | quote }}
  MYSQL_USER: {{ .Values.global.db.user | default "zoo-user" | quote }}
  MYSQL_PASS: {{ .Values.global.db.pass | default "zoo-pass" | quote }}
  MYSQL_ROOT: {{ .Values.global.db.root | default "007" | quote }}
{{- end }}