apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zoo-common.fullname" . }}-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
